# -*- coding: utf-8 -*-
"""Vera Molnar %1 Disorder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-n67E5KzFGBekHfu--C6LL8FJ3aGCYH
"""

import numpy as np
import matplotlib.pyplot as plt


SIZE = 100
DISTURBANCE_RATE = 0.01

grid = np.zeros((SIZE, SIZE))


for i in range(SIZE):
    for j in range(SIZE):
        if np.random.rand() < DISTURBANCE_RATE:
            grid[i, j] = 1


plt.figure(figsize=(10, 10))
plt.imshow(grid, cmap='binary', interpolation='none')
plt.title("Vera Molnár - %1 Düzensizlik")
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
import numpy as np


grid_size = 10
spacing = 1.0
deviation = 0.1


x_coords = []
y_coords = []

for i in range(grid_size):
    for j in range(grid_size):

        x = i * spacing
        y = j * spacing


        x += np.random.uniform(-deviation, deviation)
        y += np.random.uniform(-deviation, deviation)

        x_coords.append(x)
        y_coords.append(y)


plt.figure(figsize=(8, 8))
plt.scatter(x_coords, y_coords, color="blue", s=100)


plt.gca().set_aspect('equal', adjustable='box')
plt.axis("off")
plt.title("Vera Molnár - %1 Düzensizlik", fontsize=16, color="blue")
plt.show()